### ISSUE TITLE
[Crash]: Ticking Block Entity

### ISSUE THREAD

**Issue by Taishiro94** [Pundah/Project-Wakerife#3]
### Possible Fixes

Yes

### Modpack Version

0.0.19

### What happened?

If you connect an energy Cell from Powah and the Magmator from Powah with an Energy Pipe from Pipez, and then use a pipewrench to set the pipe at the magmator to input, you get a crash "Ticking Block entity" only fix i found was taking out pipez, and booting the world once without Pipez, after that adding pipez back so to not run other issues with quests f.e.

### Crash Log

https://gist.github.com/Taishiro94/3045afccfea461e2ab285c2c4076d379

### Latest.Log

https://gist.github.com/Taishiro94/bc592316a45fba89fcd88a6a33946a16

**Comment by Pundah** [comment]
Able to reproduce in V:0.0.18. 
Able to reproduce in V:0.0.19.

**Comment by Pundah** [comment]
Able to trace down to Mekanism. 
[[Issue #8230](https://github.com/mekanism/Mekanism/issues/8230)] reported to Mek Github.

**Comment by Pundah** [comment]
Updated Pipez
This will be resolved in V:0.0.20.
