### ISSUE TITLE
[Crash]: Rendering Item

### ISSUE THREAD

**Issue by Taishiro94** [Pundah/Project-Wakerife#4]
### Possible Fixes

Yes

### Modpack Version

0.0.19

### What happened?

Game Crashes unexpectedly for no apparent reason. 

Case 1: loaded a World from 0.0.18, checked inventory, wanted to search smth in NEI but as soon as i clicked in the search Box -> Crash

Case 2: created a new world in 0.0.19, checked inventory and search -> OK, played for some Minutes, created a Supplycamp -> OK, wanted to Craft some Wooden Picks -> Crash

### Crash Log

https://gist.github.com/Taishiro94/1eb324ac10dcb2d8750b1cc2f727768a

### Latest.Log

https://gist.github.com/Taishiro94/b9466f698fe73b16c0950cd8f76e7167

**Comment by Pundah** [comment]
Able to reproduce in V:0.0.19.

**Comment by Pundah** [comment]
Able to trace down to Mod: Embeddium.
Solution: Remove Embeddium from the client. This mod will be removed in V:0.0.20
