### ISSUE TITLE
[Bug]: hotbar scrolling issue

### ISSUE THREAD

**Issue by kenneltrainednumberone** [Pundah/Project-Wakerife#6]
### Possible Fixes

Yes

### Modpack Version

1.21.1 neoforge 21.1.56

### What happened?

When I scroll through the hotbar, it jumbles my tools around and even adds them to the crafting menu. It's nothing serious but it is rather annoying.

https://github.com/user-attachments/assets/c09b8942-6ed1-40c9-b08c-0e7e26de44a0

This is a link for the video of this occurance. If you pay attention to the hotbar, you'll notice that when I switch from the shovel to the axe, it rapidly switches the place between the axe and the shovel. I switch to the pickaxe normally and begin mining. Once I switch back to the shovel, it bugs out and places my pickaxe in my crafting menu, which you can see when I open my inventory.

I don't know if this is a specific mod that's bugging out, and I'm not sure what steps to take as I'm not very good at trouble shooting mods. If I could get some help it would be greatly appreciated.

### latest.log

https://gist.github.com/kenneltrainednumberone/3ee8e9addf168848470b634edcfc4825

**Comment by Pundah** [comment]
This is from the Plugin - [Autotools ](https://www.curseforge.com/minecraft/mc-mods/autotools)

Pressing L-Alt will disable / Renable this.


Marked as WontFix
Closing #6
